### PR TITLE
Us#46

### PR DESCRIPTION
**Pull request by pAmanda**

### CODE REVIEW

**Review by matheusoliveira30 — CHANGES_REQUESTED** [review]
Please, fix code coverage on the User component and service and fix new code issues.

**Comment by pAmanda** [comment]
Delivering use case with all criteria implemented and with 74% of test coverage.

**Comment by matheusoliveira30** [comment]
Try to fix 2 things:

1. In "create-user.component.html", the used regex does not allow names with accents, like "Luíza":

`<input type="text" class="form-control"
name="nomeCompleto" id="nomeCompleto"
placeholder="Nome Completo" [(ngModel)]="user.nomeCompleto"
 #nomeCompleto="ngModel" minlength="10"
 pattern="[a-zA-Z][a-zA-Z ]+"
required>`

2. Try creating a "generateFakeUser" function for using in unit testing. You're duplicating code in "create-user.component.spec.ts" and "user.service.spec.ts":

`let user: User = new User();
 user = new User();
 user.nomeCompleto = 'Joao Pereira';
 user.nomeUsuario = 'Joao';
 user.CEP = '72000000';
 user.cod = 0;
 user.email = 'joao@angular.com';
 user.senha = '1234567';
 user.confirmaSenha = '1234567';`

**Review by matheusoliveira30 — APPROVED** [review]

**Comment by matheusoliveira30** [comment]
Everything is fine now!

**Pull request merged**
